README.md, backend/playbackmanager.go, player/player.go, ui/browsing/albumpage.go, ui/browsing/albumspage.go, ui/browsing/artistpage.go, ui/browsing/browsingpane.go, ui/browsing/favoritespage.go, ui/browsing/nowplayingpage.go, ui/browsing/playlistpage.go, ui/browsing/router.go, ui/controller/controller.go, ui/mainwindow.go, ui/widgets/tracklist.go
Partial implementation of #33. Issue will stay open until we support reordering the play queue. This PR also contains a few misc. refactors and minor fixes, and an update to the styling of the now playing track in the tracklist view.
=> Add Now Playing page to view and edit play queue

res/supersonic-desktop.desktop
As discussed in issue #126 this pull request adds a .desktop file to the res directory.
There are, however, further considerations to be made.
1. The project compiles to a binary named supersonic, which is in conflict with an already established [subsonic server project](https://github.com/davidgfnet/supersonic-cpp).
2. This is also reflected in the AUR, where the *supersonic* package is already taken.
3. The .desktop file reflects this by changing the binary name to *supersonic-desktop* to avoid confusion and avoid conflicts.
However, this has no impact on the project as such, it would theoretically impact the people who want to install both the unrelated server implementation and this client.
The AUR, however, as well as the arch package will however need to refer to itself as …
=> Adding a proper .desktop file for future releases.

README.md
This pull request adds the build instructions for Arch Linux in the README.
As per our discussion in #126 , the Arch Linux PKGBUILD is ready and is already available in the AUR.
You can see additional details [here](https://aur.archlinux.org/packages/supersonic-desktop).
=> Adding Arch Linux build instructions to the README

ui/widgets/auxcontrols.go
Same code as https://github.com/dweymouth/supersonic/commit/a9cec173ddcd0999cfbe7f61ca15c01bd3c1cbce, but for the volume slider.
Related issue: #95
=> Temporarily add tappable behavior to volume slider until Fyne 2.4

backend/config.go, go.mod, go.sum
According to the official [migration guide](https://github.com/pelletier/go-toml/tree/v2#migrating-from-v1), there are no breaking changes that could affect this project.
Main differences are:
* `Default struct fields order`: Struct fields stop being alphabetically sorted, unless their sorting is changed in the struct definitions. Shouldn't be relevant.
* `No indentation by default`: Also not relevant for newly generated configuration files. Doesn't break reading existing configuration files.
=> Upgrade go-toml to v2

backend/playbackmanager.go
This change fixes two `TODO` comments, by scrobbling the currently playing track if it's removed from the queue, and only run OnSongChange callbacks when the playing track is affected.
=> Scrobble playing track when removed from queue

ui/browsing/albumpage.go, ui/browsing/playlistpage.go
Add in the "meatball menu" of the Album and Playlist pages the option to download the tracks of the corresponding album or playlist in a zip file. When download is clicked, a dialog window appears allowing you to choose the file name and where to save the file.
=> Ability to download album and playlist

README.md, backend/playbackmanager.go, player/player.go, ui/bottompanel.go, ui/mainwindow.go, ui/widgets/auxcontrols.go, ui/widgets/playercontrols.go
Adding the Loop functionality, along with the Player changes to support it, and a button to the player controls.
`Player` now has a `loopMode` attribute, which determines whether it should loop. At the moment, only the following modes are supported:
* `LoopNone`: Disables loop.
* `LoopAll`: Enables loop for the entire playlist queue.
This has been designed as an enum, to support other modes in the future (e.g. loop for the current track only).
It depends on the `loop` functionality provided by MPV (using the [`loop-playlist` option](https://mpv.io/manual/master/#options-loop-playlist)), so no custom logic is needed to reset the currently playing index.
=> Add Loop functionality to player controls

player/player.go, ui/theme/theme.go, ui/widgets/auxcontrols.go
This new Loop mode keeps reproducing the current track, unless it is changed using the player controls to go to the next/previous track.
As in other applications, this is set by using the "Repeat" button, which now goes from "Off" -> "Repeat All" -> "Repeat One".
=> Add functionality to repeat current track

main.go, ui/browsing/albumpage.go, ui/browsing/playlistpage.go, ui/browsing/playlistspage.go, ui/controller/controller.go, ui/widgets/gridviewitem.go, ui/widgets/tracklist.go
- fyne notication looks for the app icon to display it in the notication, so I setted the icon  in `main.go`.
- Adding ellipsis after "Download" option 
- adding the new paremeter `downloadName`
Screenshot:
Fixes #202
=> Add notification when a download is completed

backend/mediaprovider/mediaprovider.go, backend/mediaprovider/model.go, backend/mediaprovider/subsonic/subsonicmediaprovider.go, ui/browsing/albumpage.go, ui/controller/controller.go, ui/dialogs/albuminfodialog.go
Adding "Show Info" in album page's "meatball" menu. When the option is clicked a pop up appears with the album information and links to Last.fm and MusicBrainz.
Screenshot:
Fixes #105
=> Add UI for viewing the album info returned by Subsonic getAlbumInfo API

ui/widgets/tappablewrappers.go
This is being added, because testing the latest `develop` version for `fyne` fails with the following error:
```
ui/widgets/imageplaceholder.go:48:3: cannot use i.imageDisp (variable of type *TappableImage) as fyne.CanvasObject value in argument to container.NewMax: *TappableImage does not implement fyne.CanvasObject (missing method MinSize)
ui/widgets/nowplayingcard.go:51:33: cannot use n.cover (variable of type *TappableImage) as fyne.CanvasObject value in argument to container.NewBorder: *TappableImage does not implement fyne.CanvasObject (missing method MinSize)
ui/widgets/tappablewrappers.go:64:21: cannot use t (variable of type *TappableImage) as fyne.Widget value in argument to t.ExtendBaseWidget: *TappableImage does not implement fyne.Widget (missing method MinSize)
```
=> Add MinSize method to TappableImage

ui/widgets/tracklist.go
Make the Play icon easier to spot within the playing queue, by using the primary color for the current theme.
Fixes #184
=> Change playing icon color for current track

backend/app.go, backend/imagemanager.go, backend/mpris.go, backend/playbackmanager.go, go.mod, go.sum, main.go, ui/bottompanel.go, ui/mainwindow.go, ui/widgets/auxcontrols.go
Fixes: #75 
Related: #56 
This adds MPRIS support, which allows responding to media keys on Linux, remote control by `playerctl` and other tools, and integration with the now playing center in various desktop shells.
=> Add MPRIS integration

backend/mpris.go
The track id could contain invalid characters in D-Bus object path. For example, in gonic the track id is like 'tr-123' and '-' is a not valid character in D-Bus object path. This results in broken MPRIS integration.
This PR adds an encoding step before appending track id to the prefix. The base32 encoding guarantees the object path is valid.
=> Fix invalid D-Bus object path in MPRIS integration

.gitignore, backend/app.go, backend/mpmedia.go, backend/mpmedia_mac.go, backend/mpmedia_other.go, backend/mpmediabridge.h, backend/mpmediabridge.m, player/player.go
Integrates Supersonic with native MacOS APIs making Supersonic the system 'NowPlaying' app, enabling native media controls and system display of 'now playing' media info.
Feature requested & discussed via Discord.
Build has only been tested on MacOS (Specifically Sonoma 14.0 on an M2 device).
It would be a good idea to ensure that this implementation does not break the build for any other platforms.
Note: Updated to exclude C files from non-darwin platforms. This should mean that the build does not break other platforms.
Resolves #233
=> Adds integration with MacOS native media APIs

backend/mpmedia_mac.go, backend/mpmediabridge.h, backend/mpmediabridge.m
Extends the recently merged MacOS 'MPMedia' implementation to support OS 'seek' and 'duration' display.
The 'full' MacOS music widget now displays track length and allows seeking of track position.
- Supersonic responds to track position changes when the track position is changed via the OS slider
- OS slider responds to track position changes when the track position is changed via Supersonic.
Feature discussed in previous PR.
Extending the the initial implementation to support this was simpler than I initially anticipated, so here's the additional Pull Request.
=> Extends MacOS MPMedia implementation to support 'seek' & 'duration'

Makefile
Uncovered by #314, if `vapoursynth` isn't really needed, don't link it.
=> remove vapoursynth deps from `bundledeps_macos`

README.md
Currently the MacOS build section only has build instructions for homebrew. As I just finished building supersonic on a macportsonly system, I figured I'd go ahead and add the steps I used here. Let me know if the formatting needs work, I just nestled them side by side for install+build steps, but I could break them out if preferred.
=> add macports bulid instructions

res/io.github.dweymouth.supersonic.appdata.xml
It seems this is necessary in Flatpaks now. I have a build that failed with:
```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo
in dir /srv/buildbot/worker/build-x86_64-1/build (timeout 1200 secs)
watching logfiles {}
argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo'
using PTY: False
{
"errors": [
"appstream-missing-developer-name"
],
"warnings": [
"appstream-summary-too-long",
"appstream-screenshot-missing-caption"
]
}
Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter
program finished with exit code 1
elapsedTime=54.274905
```
... interestingly, that is marked as "warning" in the above documentation:
https://docs.flathub.org/docs/for-app-authors/linter/#appstream-miss …
=> add developer_name to appstream data file

backend/mpris.go
The operating system toolbar's component to control Supersonic playback had its Seek functionality broken on Linux. When playing a song, seeking for a different position from Supersonic worked as expected, but seeking from the toolbar did nothing to the current track.
I found that the underlying reason was in `MPRISHandler.SetPosition`, as the `if m.curTrackPath == trackId` always returned false.
`m.curTrackPath` was the right value, but `trackId` was wrong: On the first song being played for a tracklist, `trackId` when trying to seek was set to `/org/mpris/MediaPlayer2/TrackList/NoTrack`. When moving to the next song, `trackId` then became the Track ID of the previously played song.
Changing the call to `OnTitle()` is enough to fix the issue, as the MPRIS `Metadata()` generation depends …
=> fix: MPRIS Seek functionality on Linux

backend/mpris.go
Loop mode changes were being correctly reflected in Supersonic, when updated in the toolbar, but not the other way around. We were only missing an `Options` changes emit when loop mode is changed in Supersonic.
=> fix: Enable Loop mode sync for MPRIS

backend/app.go
When changing tracks, the toolbar display on Linux sometimes misses the track cover art, and displays a placeholder instead.
Copy same callback as the one used for MacOS, which calls `GetCoverArtUrl` first, to avoid missing cover arts.
=> fix: MPRIS broken cover art on Linux

sharedutil/sharedutil.go, ui/util/tracklistutil.go
For the scenarios where both `Filter` and `Map` are being applied, having this util should be faster, as it avoids the creation of an extra slice during the intermediate step.
=> misc: Add FilterMapSlice util

backend/config.go, backend/mediaprovider/helpers/iterators.go, backend/mediaprovider/jellyfin/iterators.go, backend/mediaprovider/mediaprovider.go, backend/mediaprovider/subsonic/artistiterator.go, backend/servermanager.go, go.mod, go.sum, ui/browsing/artistspage.go, ui/browsing/router.go, ui/controller/controller.go, ui/widgets/gridview.go
Remove custom page implementation for Artists, and instead rely on the generic `GridView` approach. This also simplifies adding new sorting/filtering options as next improvements.
The new `ArtistFilter` is a dummy implementation without any real filters at the moment.
Also, the `go-jellyfin` upgrade is needed to correctly display the album count for each artist.
=> misc: Migrate Artists page to GridView

backend/app.go, backend/playbackengine.go, backend/playbackmanager.go, ui/browsing/albumpage.go, ui/browsing/playlistpage.go, ui/browsing/playlistspage.go, ui/controller/controller.go, ui/widgets/gridview.go, ui/widgets/tracklist.go
This PR add a MenuItem "Play next" where a "Add to queue" already exists. Instead of append the tracks at the end of the play queue, it will insert them right after the currently playing track.
A corresponding logo (and unique) is still missing.
=> feat: add "Play next" MenuItem

backend/mediaprovider/jellyfin/artistiterator.go, backend/mediaprovider/jellyfin/iterators.go, backend/mediaprovider/mediaprovider.go, backend/mediaprovider/subsonic/artistiterator.go
Include both `Album Count` and `Random` sortings for the Artists page.
This change also fixes the Artist search feature in Jellyfin, which was broken because of an open issue on Jellyfin [1]. The current workaround is to do the filtering locally after receiving all results from Jellyfin API.
Also, as the Jellyfin API doesn't include a sorting option for `AlbumCount`, we need to disable pagination when that option is selected, to receive all artists, and run the sorting locally.
[1] Related issue: https://github.com/jellyfin/jellyfin/issues/8222
=> feat: Add sorting options for Artists

ui/controller/controller.go, ui/dialogs/quicksearch.go, ui/dialogs/searchdialog.go
Currently, this component is used by `QuickSearch` dialog. And then, it will be used by the "Add to playlist" dialog.
I added some setters and getters to the `QuickSearch` dialog to abstract the interaction between `QuickSearch` and `SearchDialog` from the `Controller`.
After this PR, I will implement the 'Add to playlist' dialog to incorporate the `SearchDialog`.
=> chore: Implement SearchDialog component

backend/app.go, backend/cmdlineoptions.go, backend/ipc/api.go, backend/ipc/client.go, backend/ipc/conn_other.go, backend/ipc/conn_windows.go, backend/ipc/server.go, go.mod, go.sum, main.go, ui/mainwindow.go
Adds the following command-line options
```
> ./supersonic --help
Usage of ./supersonic:
-help
print command line options and exit
-next
seek to next track
-pause
pause playback
-play
unpause or begin playback
-play-pause
toggle play/pause state
-previous
seek to previous track or beginning of current
-seek-to value
seeks to the given position in seconds in the current file (0.0 - <trackDur>)
-version
print app version and exit
-volume value
sets the playback volume (0-100)
```
=> Add ability to control playback using command-line flags

backend/mediaprovider/model.go, backend/mediaprovider/subsonic/subsonicmediaprovider.go, go.mod, go.sum, ui/dialogs/trackinfodialog.go, ui/widgets/tracklistrow.go
Adds Composer as a new column available in tracklists, and a row in the new Track Info dialog
=> Add support for composer tag

backend/app.go, backend/config.go, backend/playbackmanager.go
When playing random songs supersonic had a hardcoded value of 100. This was very small for my taste. This PR add the option to configure it. 
I found out, however, that the current algorithm is worryingly slow. With a value of 1000 it takes more than 20 seconds on my computer. Recovering the queue when restarting supersonic is also very slow.
=> add option to configure queue size

ui/browsing/artistpage.go
This needs some more testing, since there are some things I'm not yet quite sure about
- In the `Artist` model, `ID` and `CoverArtID` seem to be the same thing, no? (the id's differ, but both result in the correct image)
- Why does `ArtistPageHeader` in its `Update` method have a nil check for `artist == nil`, whereas, e.g., `AlbumPageHeader` doesn't. Is this nil check even necessary?
- There also was an `if artist.CoverArtID == ""` check which I removed, as far as my testing goes it also is not required.
=> feat: fetch full size artist cover on tapped

backend/app.go, backend/lrclib.go, backend/mediaprovider/model.go, ui/browsing/nowplayingpage.go, ui/browsing/router.go
Adds cache for the following reasons:
- Reduce unnecessary API calls
- Allows showing lyrics if external server aren't reachable
- Slightly improves on privacy, since the server only sees the first time a song gets played
My go has become a bit rusty over the time so please feel free to suggest a cleaner way of this implementation if you aren't happy with my approach
=> Add caching for lrclib lyrics

backend/app.go, backend/config.go, backend/lrclib.go
Depends on #544 
(I'll rebase this PR once the other one is merged)
Since Lrclib [can be selfhosted](https://github.com/tranxuanthang/lrclib), it is possible to use a different server than the public one.
This PR allows setting a different lrclib server URL in the config.
Reasons to do so:
- Privacy
- Personal lyrics database (since lrclib.net doesn't allow adding new lyrics)
=> Custom lrclib url config

ui/widgets/auxcontrols.go
For some reason my compositor reports a delta of 70 in scroll events so the volume slider makes a large 35% jump every scroll notch. Clamping to 10% seems reasonable.
=> Clamp volume slider scrolling

backend/app.go
Instead of using the NowPlaying() metadata (which is sometimes nil, and so would require some error handling), we now use the PlaybackStatus().
Notice that PlaybackStatus() will return information from the pendingPlayerChangeStatus, which if I understand correctly is the track we're *about* to start playing.
Fixes #590, fixes #581, fixes #562
=> Fix crash in Windows SMTC

ui/browsing/trackspage.go
This changes a statement from Println, to Printf, as it seems the original intention was to format the error.
=> Change log.Println statement to log.Printf

.github/workflows/lints.yml, .golangci.yml, Makefile, backend/player/dlna/dlnaplayer.go, backend/player/jukebox/jukeboxplayer.go, ui/browsing/nowplayingpage.go, ui/widgets/imagepopup.go
This adds `golangci-lint` as a linter for the project, through a configuration, a
makefile recipe, and ci.  I've reverted one of the fixes to demonstrate the ci fail,
and will remove said commit if we deem these changes worthy of merging. 
If something like this is not desired for the project, that's cool too, let me know.
If this is OK, I can start enabling the rest of the lints and submit more patches.
Cheers!
Edit: here's what it looks like: https://github.com/psyomn/supersonic/actions/workflows/build-appimage.yml 
I think annotations should show up in PRs if I understood the actions correctly.
=> Add golangci lint and unused lint
