- ui/browsingpane.go
> Fix deadlock with search entry

- backend/app.go
- backend/playbackmanager.go
- backend/util/stopwatch.go
- ui/albumgrid.go
> Add scrobbling of played tracks

- backend/app.go
- ui/albumgrid.go
- ui/albumspage.go
- ui/artistpage.go
- ui/browsingpane.go
- ui/mainwindow.go
- ui/router.go
- ui/widgets/albumcard.go
- ui/widgets/customhyperlink.go
Partial implementation of #9. Still need to add to the page header (album count, artist info, etc.)
> Add artist page and navigation

- backend/albumiterator.go
- backend/playbackmanager.go
- player/player.go
- ui/albumgrid.go
- ui/albumpage.go
- ui/albumspage.go
- ui/artistpage.go
- ui/browsingpane.go
- ui/layout/columnslayout.go
- ui/router.go
- ui/widgets/albumcard.go
- ui/widgets/tracklist.go
Partial implementation of #8 - album page is just title and tracklist. Leaving issue open until cover, album artist link, num tracks, total time are added
> Add album page with track listing

- backend/albumiterator.go
- ui/browsing/albumpage.go
- ui/browsing/genrepage.go
- ui/browsing/router.go
> Add Genre page with album grid

- README.md
- backend/playbackmanager.go
- ui/browsing/playlistpage.go
- ui/browsing/playlistspage.go
- ui/browsing/router.go
- ui/mainwindow.go
- ui/widgets/tracklist.go
Create and edit playlist support will come later
> Add support for browsing and playing existing playlists

- backend/albumiterator.go
- backend/librarymanager.go
- backend/playbackmanager.go
- backend/servermanager.go
- go.mod
- go.sum
- ui/bottompanel.go
- ui/browsing/albumpage.go
- ui/browsing/artistpage.go
- ui/browsing/artistsgenrespage.go
- ui/browsing/browsingpane.go
- ui/browsing/favoritespage.go
- ui/browsing/genrepage.go
- ui/browsing/playlistpage.go
- ui/browsing/playlistspage.go
- ui/browsing/router.go
- ui/controller/controller.go
- ui/dialogs/addtoplaylistdialog.go
- ui/mainwindow.go
- ui/os/keymodifiers_darwin.go
- ui/os/keymodifiers_default.go
- ui/util/listselectionmanager.go
- ui/util/util.go
- ui/widgets/albumcard.go
- ui/widgets/albumgrid.go
- ui/widgets/tracklist.go
Partial implementation of #21 (reorder tracks, delete playlists, update playlist metadata not yet supported). Probably enough to target for alpha release though so I'll remove the alpha-release milestone from #21.
> Add support for adding/removing tracks from playlists, creating new playlists

- backend/playbackmanager.go
- backend/servermanager.go
- main.go
- player/player.go
- ui/browsing/albumpage.go
- ui/browsing/browsingpane.go
- ui/browsing/nowplayingpage.go
- ui/browsing/playlistpage.go
- ui/controller/controller.go
- ui/dialogs/addeditserverdialog.go
- ui/dialogs/logindialog.go
- ui/layouts/columnslayout.go
- ui/mainwindow.go
- ui/widgets/tracklist.go
Implementation of #32. This PR also contains a few unrelated refactors, and adds additional columns to the tracklist view.
> Add ability to log out of server, edit server connection

- ui/browsing/albumpage.go
- ui/browsing/albumspage.go
- ui/browsing/artistpage.go
- ui/browsing/artistsgenrespage.go
- ui/browsing/favoritespage.go
- ui/browsing/genrepage.go
- ui/browsing/nowplayingpage.go
- ui/browsing/playlistpage.go
- ui/browsing/router.go
Fixes #41. Also fixes a semi-long standing regression that albums could not be played directly from the Genre page.
> Ensure server requests happen in goroutines in UI callbacks

- ui/widgets/tracklist.go
Workaround for #45 - on Linux, tracklist selection will always operate in Ctrl+click mode. Will remove alpha-release blocker from #45 but keep issue open.
> Workaround for tracklist selection on Linux

- backend/playbackmanager.go
- ui/browsing/genrepage.go
> Add button to play random songs to genre page

- backend/config.go
- ui/browsing/artistpage.go
- ui/browsing/router.go
- ui/widgets/toggletext.go
> Add Top Tracks view to Artist page

- backend/app.go
- backend/config.go
- backend/playbackmanager.go
- player/libmpv.go
- player/player.go
> Add ReplayGain support

- go.mod
- go.sum
- ui/widgets/tracklist.go
> fix tracklist multi-select behavior on Linux/X11

- backend/app.go
- backend/playbackmanager.go
- player/player.go
- ui/controller/controller.go
- ui/dialogs/settingsdialog.go
- ui/mainwindow.go
- ui/widgets/textrestrictedentry.go
> Add settings dialog

- CHANGELOG.md
- backend/app.go
- backend/config.go
- backend/playbackmanager.go
- go.mod
- go.sum
- main.go
- ui/dialogs/settingsdialog.go
- ui/mainwindow.go
> Add system tray menu and close to tray option

- player/player.go
This was requested in issue #112.
> WIP: add debugging statements when playing

- res/io.github.dweymouth.supersonic.appdata.xml
> import Appstream data file from Flatpak package

- CHANGELOG.md
- backend/albumiterator.go
- backend/config.go
- backend/librarymanager.go
- backend/searchiterbase.go
- backend/trackiterator.go
- ui/browsing/router.go
- ui/browsing/trackspage.go
- ui/controller/routes.go
- ui/mainwindow.go
- ui/widgets/tracklist.go
- ui/widgets/tracklistloader.go
> Add searchable "All Tracks" page

- res/supersonic-desktop.desktop
This allows the application to be listed in menus under music players / multimedia categories.
> Add Categories entry to Desktop Entry file

- ui/browsing/browsingpane.go
I'm fairly new to Go and and the Supersonic codebase, so feedback is welcome.
Closes #166.
> Disable history btns when unable to navigate

- backend/app.go
- backend/config.go
- backend/imagemanager.go
- backend/servermanager.go
- main.go
- ui/controller/controller.go
- ui/dialogs/addeditserverdialog.go
- ui/dialogs/addtoplaylistdialog.go
- ui/dialogs/editplaylistdialog.go
- ui/dialogs/logindialog.go
- ui/mainwindow.go
> Add multi-server support

- ui/browsing/browsingpane.go
Adding home buttom to the top bar, which goes to the startup page. 
It also avoids unnecessary refreshes when the current page is the home page.
> Added home icon in BrowsingPane

- backend/mediaprovider/mediaprovider.go
- backend/mediaprovider/subsonic/subsonicmediaprovider.go
- go.mod
- go.sum
- ui/controller/controller.go
- ui/widgets/tracklist.go
- Adding the option to download the selected track or tracks. When the download is clicked it opens a dialog that lets you choose where you want to save the track and the file name (by default the file name is the track number, the track name and the extension, example "03 - my song.mp3").
If there are many tracks selected it will open the dialog one time and it will download a zip file with the selected tracks.
- Next steps: download an album and a playlist using zip
> Ability to download tracks

- ui/browsing/playlistspage.go
- ui/controller/controller.go
- ui/widgets/gridview.go
- ui/widgets/gridviewitem.go
Adding the option to download the album or tracks in grid view from Artist and Album pages.
> Ability to download from grid

- backend/mpris.go
> Add `ContentCreated`, `UseCount` to MPRIS result

- ui/browsing/genrespage.go
- ui/browsing/playlistspage.go
> Add sorting to playlists and genres list views

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows.yml
- backend/app.go
- backend/mediaprovider/helpers/iterators.go
- backend/util/util.go
- go.mod
- go.sum
- sharedutil/sharedutil.go
- sharedutil/sharedutil_test.go
- ui/browsing/albumspage.go
- ui/browsing/nowplayingpage.go
- ui/browsing/playlistpage.go
- ui/theme/theme.go
- ui/theme/themefile.go
- ui/util/tracklistutil.go
- ui/widgets/albumfilterbutton.go
- ui/widgets/gridviewitem.go
- ui/widgets/tracklist.go
Upgrade to 1.21 as 1.20 is now unmaintained.
Most changes are related to the new `slices` package from standard library, which can replace some existing custom functions.
> misc: Upgrade Go to v1.21

- backend/mediaprovider/helpers/iterators.go
- backend/mediaprovider/jellyfin/iterators.go
- backend/mediaprovider/jellyfin/jellyfinmediaprovider.go
- backend/mediaprovider/mediaprovider.go
- backend/mediaprovider/subsonic/artistiterator.go
- backend/mediaprovider/subsonic/subsonicmediaprovider.go
- go.mod
- ui/browsing/artistspage.go
First step towards improving sorting for Artists. Use the same iterator approach as albums and tracks.
> misc: Implement Iterator approach for artists

- backend/mediaprovider/mediaprovider.go
- backend/mediaprovider/model.go
- backend/mediaprovider/subsonic/subsonicmediaprovider.go
- go.mod
- go.sum
- ui/browsing/nowplayingpage.go
- ui/browsing/router.go
- ui/controller/routes.go
- ui/widgets/lyricsviewer.go
> Add lyrics viewer

- ui/bottompanel.go
- ui/widgets/nowplayingcard.go
Small change to `NowPlayingCard`, to be able to use more Track properties in the future (e.g. favorite status).
> misc: Make NowPlayingCard.Update receive Track object

- ui/layouts/gridlayoutcustompadding.go
- ui/layouts/hboxcustompadding.go
- ui/layouts/maxpadlayout.go
- ui/layouts/vboxcustompadding.go
Specific commits ported, to update the layouts and reduce differences with upstream Fyne code:
* https://github.com/fyne-io/fyne/commit/a9a66f60d2167d7945bcf7718a781335541317c0
* https://github.com/fyne-io/fyne/commit/2cde868904092382ca5f645802ee9d444d8ae6e8
* https://github.com/fyne-io/fyne/commit/99fa7e3a7dc83dd273ad366cc7d336a1e1cee5f6
* https://github.com/fyne-io/fyne/commit/4ea8a5762f1744401ede9f7bd35b3b75890f925e
> misc: Port latest Fyne layout changes

- backend/mediaprovider/helpers/other.go
- backend/mediaprovider/model.go
- backend/mediaprovider/subsonic/subsonicmediaprovider.go
- backend/mpris.go
- go.mod
- go.sum
- ui/controller/controller.go
- ui/dialogs/trackinfodialog.go
- ui/widgets/tracklist.go
> Add track info dialog

- res/translations/en.json
- res/translations/zh.json
- res/translations/zhHans.json
- res/translations/zhHant.json
- ui/dialogs/trackinfodialog.go
- ui/widgets/gridview.go
- ui/widgets/nowplayingcard.go
- ui/widgets/playqueuelist.go
- ui/widgets/tracklist.go
> i18n: update i18n references on menu labels, update chinese translation

- backend/mediaprovider/subsonic/trackiterator.go
change the default sort order of trackPages to the recently added
> change the default sort order of trackPages to the recently added

- backend/app.go
- backend/ipc/server.go
- backend/mediaprovider/mediaprovider.go
- backend/mediaprovider/subsonic/jukebox.go
- backend/mpris.go
- backend/playbackcommands.go
- backend/playbackengine.go
- backend/playbackmanager.go
- backend/player/jukebox/jukeboxplayer.go
- backend/player/mpv/player.go
- backend/player/player.go
- ui/bottompanel.go
- ui/controller/connectactions.go
- ui/mainwindow.go
.. if the UI can generate them faster than the player can respond to them
> Prep for Jukebox mode - add queue to accumulate playback commands

- backend/config.go
- main.go
- res/translations.go
- res/translations/en.json
- res/translations/es.json
- res/translations/fr.json
- res/translations/it.json
- res/translations/ja.json
- res/translations/pl.json
- res/translations/pt_BR.json
- res/translations/ro.json
- res/translations/zh.json
- res/translations/zhHans.json
- res/translations/zhHant.json
- ui/dialogs/settingsdialog.go
Adds a Language drop-down to the settings dialog:
> Add option to override app language detection

- ui/mainwindow.go
Stopgap solution for #316 on Linux as long as `notify-send` is in `$PATH`. Notifications will include cover art and automatically dismiss after 10 seconds.
> Use notify-send for notifications on Linux

- backend/config.go
- backend/playbackmanager.go
- ui/browsing/albumspage.go
- ui/browsing/artistpage.go
- ui/browsing/artistspage.go
- ui/browsing/genrepage.go
- ui/browsing/gridviewpage.go
- ui/widgets/iconbutton.go
- ui/widgets/optionbutton.go
- ui/widgets/sortchooserbutton.go
> Add ability to shuffle by albums (to Albums page and Genre page)

- ui/theme/theme.go
fix for bug, light button colors in a light theme turn dark when hovering, issue #451
> bug fix for issue #451

- BUILD.md
- Makefile
- backend/mpmedia_mac.go
- backend/player/mpv/peaks_mac.go
- go.mod
- go.sum
I think this would allow it to be listed on https://apps.fyne.io.
I do need to check this works on Linux and Windows without setup too...
It will also need to rely on the patched go-mpv once the PR there is landed.
> Build on a mac without environment variables

- backend/config.go
- res/bundled.go
- res/bundled_gen.sh
- res/icons/publicdomain/sidebar.svg
- res/translations/en.json
- ui/browsing/browsingpane.go
- ui/container/split.go
- ui/mainwindow.go
- ui/sidebar.go
- ui/theme/theme.go
- ui/toolbar.go
Implements #680 
Drag-and-drop to queue is out of scope for this PR for now, but will come later
> Add toggleable play queue sidebar
